### ISSUE TITLE
我用的是1.0的，我一放进去就出错了

### ISSUE THREAD

**Issue by rabbitLove520** [qq915458022/Dalcho#2]
`Fatal error: Uncaught TypeError: Argument 1 passed to Typecho_Common::exceptionHandle() must be an instance of Exception, instance of ParseError given in D:\nginx_project\typecho\var\Typecho\Common.php:235 Stack trace: #0 [internal function]: Typecho_Common::exceptionHandle(Object(ParseError)) #1 {main} thrown in D:\nginx_project\typecho\var\Typecho\Common.php on line 235`

这让我有点生气

**Comment by tearfulDalvik** [comment]
把 Typecho 更新到最新版本并安装 Dalcho 的最新版本试试，先关掉所有插件

从这个 Stack Trace 来看似乎和主题木有关系啊

**Comment by tearfulDalvik** [comment]
鉴于长时间未回复，已将此问题关闭
如果仍然存在此问题，请 reopen 此问题
